[project]
name = "arc"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "cellpose>=4.0.8",
    "jax[cuda13]>=0.9.0; sys_platform == 'linux'",
    "jax>=0.9.0; sys_platform != 'linux'",
    "napari[pyside6]>=0.6.6",
    "numba>=0.60",
    "numpy>=2.0",
    "opencv-python>=4.13.0.90",
    "pandas>=3.0.0",
    "pyside6",
    "rtree>=1.4.1",
    "scikit-learn>=1.8.0",
    "seaborn>=0.13.2",
    "trimesh>=4.11.1",
    "umap-learn>=0.5.11",
    "vedo",
    "vtk>=9.5.2",
    "py-spy>=0.4.1",
    "fast-simplification>=0.1.13",
    "pyarrow>=23.0.1",
]

[dependency-groups]
dev = [
    "ipykernel>=6.31.0",
    "pyinstaller>=6.18.0",
    "pytest>=8.0",
]
