[project]
name = "arc"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "cellpose>=4.0.8",
    "jax[cuda13]>=0.9.0; sys_platform == 'linux'",
    "jax>=0.9.0; sys_platform != 'linux'",
    "napari>=0.6.6",
    "numba>=0.60",
    "numpy>=2.0",
    "opencv-python>=4.13.0.90",
    "pandas>=3.0.0",
    "pyqt5>=5.15.11",
    "pyside6",
    "rtree>=1.4.1",
    "scikit-learn>=1.8.0",
    "seaborn>=0.13.2",
    "trimesh>=4.11.1",
    "umap-learn>=0.5.11",
    "vedo",
    "vtk>=9.5.2",
]

[project.scripts]
arc = "arc.main:main"

[dependency-groups]
dev = [
    "pyinstaller>=6.18.0",
]
